services:
  server:
    build:
      context: ./Server
    image: lucidlegend/umabreeder-server:latest
    environment:
      FLASK_APP_MODULE: "main:app"
      PORT: "5000"
    ports:
      - "5000:5000"

  client-dev:
    profiles: ["dev"]
    build:
      context: ./Client
      dockerfile: Dockerfile.dev
    image: lucidlegend/umabreeder-client-dev:latest
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "150"
    depends_on:
      - server

    develop:
      watch:
        - action: sync
          path: ./Client/src
          target: /app/src
        - action: sync
          path: ./Client/public
          target: /app/public
        - action: rebuild
          path: ./Client/package.json
        - action: rebuild
          path: ./Client/package-lock.json

  client-prod:
    profiles: ["prod"]
    build:
      context: ./Client
      dockerfile: Dockerfile.prod
    image: lucidlegend/umabreeder-client:latest
    ports:
      - "5173:80"
    depends_on:
      - server
